version: '2.1'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
  api:
    build: ./packages/api
    ports:
      - 4000:4000
    links: 
      - db
      - pubsub
    environment:
      REDIS_HOST: pubsub
  # ui:
  #   build: ./packages/rx
  #   ports: 
  pubsub:
    image: redis
    ports:
      - "6379:6379"